FROM node:16-alpine AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn generate

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY deployment/nginx.conf /etc/nginx/sites-available/default

RUN mkdir -p /etc/nginx/sites-enabled && ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
